<?php

namespace Container9xL83Gh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M_83h4Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.M_.83h4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M_.83h4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'prodotto' => ['privates', '.errored..service_locator.M_.83h4.App\\Entity\\Prodotto', NULL, 'Cannot autowire service ".service_locator.M_.83h4": it references class "App\\Entity\\Prodotto" but no such service exists.'],
        ], [
            'prodotto' => 'App\\Entity\\Prodotto',
        ]);
    }
}
