<?php

namespace Container9xL83Gh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UkjguuXService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ukjguuX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ukjguuX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'prodotto' => ['privates', '.errored..service_locator.ukjguuX.App\\Entity\\Prodotto', NULL, 'Cannot autowire service ".service_locator.ukjguuX": it references class "App\\Entity\\Prodotto" but no such service exists.'],
        ], [
            'em' => '?',
            'prodotto' => 'App\\Entity\\Prodotto',
        ]);
    }
}
