<?php

namespace Container9xL83Gh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\CalendarController' shared autowired service.
     *
     * @return \App\Controller\Api\CalendarController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\CalendarController'] = $instance = new \App\Controller\Api\CalendarController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\Api\\CalendarController', $container));

        return $instance;
    }
}
