<?php

namespace Container9xL83Gh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckExpirationsCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\CheckExpirationsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\CheckExpirationsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:check-expirations', [], 'Controlla le stock entry in scadenza nelle prossime N giornate (default 7).', false, #[\Closure(name: 'App\\Command\\CheckExpirationsCommand')] function () use ($container): \App\Command\CheckExpirationsCommand {
            return ($container->privates['App\\Command\\CheckExpirationsCommand'] ?? $container->load('getCheckExpirationsCommandService'));
        });
    }
}
