<?php

namespace Container9xL83Gh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProdottoTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ProdottoType' shared autowired service.
     *
     * @return \App\Form\ProdottoType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ProdottoType'] = new \App\Form\ProdottoType($container->parameters['pantry_categories']);
    }
}
