<?php

namespace Container9xL83Gh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProdottoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ProdottoRepository' shared autowired service.
     *
     * @return \App\Repository\ProdottoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ProdottoRepository'] = new \App\Repository\ProdottoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
