<?php

namespace Container9xL83Gh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProdotto3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.ukjguuX.App\Entity\Prodotto' shared service.
     *
     * @return \App\Entity\Prodotto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ukjguuX": it references class "App\\Entity\\Prodotto" but no such service exists.');
    }
}
