<?php

namespace Container9xL83Gh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedSampleDataCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\SeedSampleDataCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\SeedSampleDataCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:seed-sample', [], 'Crea alcuni dati di esempio (Prodotto + StockEntry) per testare il calendario.', false, #[\Closure(name: 'App\\Command\\SeedSampleDataCommand')] function () use ($container): \App\Command\SeedSampleDataCommand {
            return ($container->privates['App\\Command\\SeedSampleDataCommand'] ?? $container->load('getSeedSampleDataCommandService'));
        });
    }
}
