<?php

namespace Container9xL83Gh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScadenzeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ScadenzeController' shared autowired service.
     *
     * @return \App\Controller\ScadenzeController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ScadenzeController'] = $instance = new \App\Controller\ScadenzeController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ScadenzeController', $container));

        return $instance;
    }
}
