<?php

namespace Container9xL83Gh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockEntryRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\StockEntryRepository' shared autowired service.
     *
     * @return \App\Repository\StockEntryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\StockEntryRepository'] = new \App\Repository\StockEntryRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
