<?php

namespace Container9xL83Gh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedSampleDataCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\SeedSampleDataCommand' shared autowired service.
     *
     * @return \App\Command\SeedSampleDataCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\SeedSampleDataCommand'] = $instance = new \App\Command\SeedSampleDataCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app:seed-sample');
        $instance->setDescription('Crea alcuni dati di esempio (Prodotto + StockEntry) per testare il calendario.');

        return $instance;
    }
}
