<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9xL83Gh\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9xL83Gh/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container9xL83Gh.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container9xL83Gh\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container9xL83Gh\App_KernelProdContainer([
    'container.build_hash' => '9xL83Gh',
    'container.build_id' => 'c4bdb6de',
    'container.build_time' => 1761504126,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9xL83Gh');
