<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_calendar_events' => [[], ['_controller' => 'App\\Controller\\Api\\CalendarController::events'], [], [['text', '/api/calendar-events']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/']], [], [], []],
    'app_prodotto_index' => [[], ['_controller' => 'App\\Controller\\ProdottoController::index'], [], [['text', '/prodotto/']], [], [], []],
    'app_prodotto_new' => [[], ['_controller' => 'App\\Controller\\ProdottoController::new'], [], [['text', '/prodotto/new']], [], [], []],
    'app_prodotto_show' => [['id'], ['_controller' => 'App\\Controller\\ProdottoController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/prodotto']], [], [], []],
    'app_prodotto_fragment' => [['id'], ['_controller' => 'App\\Controller\\ProdottoController::fragment'], [], [['text', '/fragment'], ['variable', '/', '[^/]++', 'id', true], ['text', '/prodotto']], [], [], []],
    'app_prodotto_edit' => [['id'], ['_controller' => 'App\\Controller\\ProdottoController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/prodotto']], [], [], []],
    'app_prodotto_delete' => [['id'], ['_controller' => 'App\\Controller\\ProdottoController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/prodotto']], [], [], []],
    'app_prodotto_delete_all' => [[], ['_controller' => 'App\\Controller\\ProdottoController::deleteAll'], [], [['text', '/prodotto/delete-all']], [], [], []],
    'app_prodotto_delete_selected' => [[], ['_controller' => 'App\\Controller\\ProdottoController::deleteSelected'], [], [['text', '/prodotto/delete-selected']], [], [], []],
    'app_scadenze_index' => [[], ['_controller' => 'App\\Controller\\ScadenzeController::index'], [], [['text', '/scadenze/']], [], [], []],
];
