<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE0ROiWl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE0ROiWl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE0ROiWl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE0ROiWl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE0ROiWl\App_KernelDevDebugContainer([
    'container.build_hash' => 'E0ROiWl',
    'container.build_id' => 'fcf18773',
    'container.build_time' => 1761675593,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE0ROiWl');
