<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'api_calendar_events' => [[], ['_controller' => 'App\\Controller\\Api\\CalendarController::events'], [], [['text', '/api/calendar-events']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/']], [], [], []],
    'app_prodotto_index' => [[], ['_controller' => 'App\\Controller\\ProdottoController::index'], [], [['text', '/prodotto/']], [], [], []],
    'app_prodotto_new' => [[], ['_controller' => 'App\\Controller\\ProdottoController::new'], [], [['text', '/prodotto/new']], [], [], []],
    'app_prodotto_show' => [['id'], ['_controller' => 'App\\Controller\\ProdottoController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/prodotto']], [], [], []],
    'app_prodotto_fragment' => [['id'], ['_controller' => 'App\\Controller\\ProdottoController::fragment'], [], [['text', '/fragment'], ['variable', '/', '[^/]++', 'id', true], ['text', '/prodotto']], [], [], []],
    'app_prodotto_edit' => [['id'], ['_controller' => 'App\\Controller\\ProdottoController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/prodotto']], [], [], []],
    'app_prodotto_delete' => [['id'], ['_controller' => 'App\\Controller\\ProdottoController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/prodotto']], [], [], []],
    'app_prodotto_delete_all' => [[], ['_controller' => 'App\\Controller\\ProdottoController::deleteAll'], [], [['text', '/prodotto/delete-all']], [], [], []],
    'app_prodotto_delete_selected' => [[], ['_controller' => 'App\\Controller\\ProdottoController::deleteSelected'], [], [['text', '/prodotto/delete-selected']], [], [], []],
    'app_prodotto_notifications' => [['id'], ['_controller' => 'App\\Controller\\ProdottoController::updateNotifications'], [], [['text', '/notifications'], ['variable', '/', '[^/]++', 'id', true], ['text', '/prodotto']], [], [], []],
    'app_scadenze_index' => [[], ['_controller' => 'App\\Controller\\ScadenzeController::index'], [], [['text', '/scadenze/']], [], [], []],
];
