<?php

namespace ContainerE0ROiWl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PWeh_MfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pWeh.mf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pWeh.mf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'prodotto' => ['privates', '.errored..service_locator.pWeh.mf.App\\Entity\\Prodotto', NULL, 'Cannot autowire service ".service_locator.pWeh.mf": it references class "App\\Entity\\Prodotto" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'prodotto' => 'App\\Entity\\Prodotto',
        ]);
    }
}
