<?php

namespace ContainerE0ROiWl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IIjin0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i_ijin0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i_ijin0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\StockEntryRepository', 'getStockEntryRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\StockEntryRepository',
        ]);
    }
}
