<?php

namespace ContainerE0ROiWl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Z3EuDvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..z3EuDv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..z3EuDv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'repo' => ['privates', 'App\\Repository\\StockEntryRepository', 'getStockEntryRepositoryService', true],
        ], [
            'em' => '?',
            'mailer' => '?',
            'repo' => 'App\\Repository\\StockEntryRepository',
        ]);
    }
}
