<?php

namespace ContainerE0ROiWl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TxxB_U5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.txxB.u5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.txxB.u5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Api\\CalendarController::events' => ['privates', '.service_locator.i_ijin0', 'get_ServiceLocator_IIjin0Service', true],
            'App\\Controller\\ProdottoController::delete' => ['privates', '.service_locator.ukjguuX', 'get_ServiceLocator_UkjguuXService', true],
            'App\\Controller\\ProdottoController::deleteAll' => ['privates', '.service_locator.kor_zoT', 'get_ServiceLocator_KorZoTService', true],
            'App\\Controller\\ProdottoController::deleteSelected' => ['privates', '.service_locator.kor_zoT', 'get_ServiceLocator_KorZoTService', true],
            'App\\Controller\\ProdottoController::edit' => ['privates', '.service_locator.pWeh.mf', 'get_ServiceLocator_PWeh_MfService', true],
            'App\\Controller\\ProdottoController::fragment' => ['privates', '.service_locator.M_.83h4', 'get_ServiceLocator_M_83h4Service', true],
            'App\\Controller\\ProdottoController::index' => ['privates', '.service_locator.DuoeDEB', 'get_ServiceLocator_DuoeDEBService', true],
            'App\\Controller\\ProdottoController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ProdottoController::show' => ['privates', '.service_locator.M_.83h4', 'get_ServiceLocator_M_83h4Service', true],
            'App\\Controller\\ProdottoController::updateNotifications' => ['privates', '.service_locator.ukjguuX', 'get_ServiceLocator_UkjguuXService', true],
            'App\\Controller\\ScadenzeController::index' => ['privates', '.service_locator..z3EuDv', 'get_ServiceLocator__Z3EuDvService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\Api\\CalendarController:events' => ['privates', '.service_locator.i_ijin0', 'get_ServiceLocator_IIjin0Service', true],
            'App\\Controller\\ProdottoController:delete' => ['privates', '.service_locator.ukjguuX', 'get_ServiceLocator_UkjguuXService', true],
            'App\\Controller\\ProdottoController:deleteAll' => ['privates', '.service_locator.kor_zoT', 'get_ServiceLocator_KorZoTService', true],
            'App\\Controller\\ProdottoController:deleteSelected' => ['privates', '.service_locator.kor_zoT', 'get_ServiceLocator_KorZoTService', true],
            'App\\Controller\\ProdottoController:edit' => ['privates', '.service_locator.pWeh.mf', 'get_ServiceLocator_PWeh_MfService', true],
            'App\\Controller\\ProdottoController:fragment' => ['privates', '.service_locator.M_.83h4', 'get_ServiceLocator_M_83h4Service', true],
            'App\\Controller\\ProdottoController:index' => ['privates', '.service_locator.DuoeDEB', 'get_ServiceLocator_DuoeDEBService', true],
            'App\\Controller\\ProdottoController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ProdottoController:show' => ['privates', '.service_locator.M_.83h4', 'get_ServiceLocator_M_83h4Service', true],
            'App\\Controller\\ProdottoController:updateNotifications' => ['privates', '.service_locator.ukjguuX', 'get_ServiceLocator_UkjguuXService', true],
            'App\\Controller\\ScadenzeController:index' => ['privates', '.service_locator..z3EuDv', 'get_ServiceLocator__Z3EuDvService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\Api\\CalendarController::events' => '?',
            'App\\Controller\\ProdottoController::delete' => '?',
            'App\\Controller\\ProdottoController::deleteAll' => '?',
            'App\\Controller\\ProdottoController::deleteSelected' => '?',
            'App\\Controller\\ProdottoController::edit' => '?',
            'App\\Controller\\ProdottoController::fragment' => '?',
            'App\\Controller\\ProdottoController::index' => '?',
            'App\\Controller\\ProdottoController::new' => '?',
            'App\\Controller\\ProdottoController::show' => '?',
            'App\\Controller\\ProdottoController::updateNotifications' => '?',
            'App\\Controller\\ScadenzeController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Api\\CalendarController:events' => '?',
            'App\\Controller\\ProdottoController:delete' => '?',
            'App\\Controller\\ProdottoController:deleteAll' => '?',
            'App\\Controller\\ProdottoController:deleteSelected' => '?',
            'App\\Controller\\ProdottoController:edit' => '?',
            'App\\Controller\\ProdottoController:fragment' => '?',
            'App\\Controller\\ProdottoController:index' => '?',
            'App\\Controller\\ProdottoController:new' => '?',
            'App\\Controller\\ProdottoController:show' => '?',
            'App\\Controller\\ProdottoController:updateNotifications' => '?',
            'App\\Controller\\ScadenzeController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
