<?php

namespace ContainerE0ROiWl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckExpirationsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CheckExpirationsCommand' shared autowired service.
     *
     * @return \App\Command\CheckExpirationsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CheckExpirationsCommand.php';

        $container->privates['App\\Command\\CheckExpirationsCommand'] = $instance = new \App\Command\CheckExpirationsCommand(($container->privates['App\\Repository\\StockEntryRepository'] ?? $container->load('getStockEntryRepositoryService')));

        $instance->setName('app:check-expirations');
        $instance->setDescription('Controlla le stock entry in scadenza nelle prossime N giornate (default 7).');

        return $instance;
    }
}
