<?php

namespace ContainerE0ROiWl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckExpirationsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CheckExpirationsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\CheckExpirationsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:check-expirations', [], 'Controlla le stock entry in scadenza nelle prossime N giornate (default 7).', false, #[\Closure(name: 'App\\Command\\CheckExpirationsCommand')] function () use ($container): \App\Command\CheckExpirationsCommand {
            return ($container->privates['App\\Command\\CheckExpirationsCommand'] ?? $container->load('getCheckExpirationsCommandService'));
        });
    }
}
