<?php

namespace ContainerE0ROiWl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProdottoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.M_.83h4.App\Entity\Prodotto' shared service.
     *
     * @return \App\Entity\Prodotto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.M_.83h4": it references class "App\\Entity\\Prodotto" but no such service exists.');
    }
}
