<?php

namespace ContainerE0ROiWl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedSampleDataCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\SeedSampleDataCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\SeedSampleDataCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:seed-sample', [], 'Crea alcuni dati di esempio (Prodotto + StockEntry) per testare il calendario.', false, #[\Closure(name: 'App\\Command\\SeedSampleDataCommand')] function () use ($container): \App\Command\SeedSampleDataCommand {
            return ($container->privates['App\\Command\\SeedSampleDataCommand'] ?? $container->load('getSeedSampleDataCommandService'));
        });
    }
}
