<?php

namespace ContainerE0ROiWl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedSampleDataCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SeedSampleDataCommand' shared autowired service.
     *
     * @return \App\Command\SeedSampleDataCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SeedSampleDataCommand.php';

        $container->privates['App\\Command\\SeedSampleDataCommand'] = $instance = new \App\Command\SeedSampleDataCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setName('app:seed-sample');
        $instance->setDescription('Crea alcuni dati di esempio (Prodotto + StockEntry) per testare il calendario.');

        return $instance;
    }
}
