<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StockEntry extends \App\Entity\StockEntry implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'posizione' => [parent::class, 'posizione', null, 16],
        "\0".parent::class."\0".'prodotto' => [parent::class, 'prodotto', null, 16],
        "\0".parent::class."\0".'quantita' => [parent::class, 'quantita', null, 16],
        "\0".parent::class."\0".'scadenza' => [parent::class, 'scadenza', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'posizione' => [parent::class, 'posizione', null, 16],
        'prodotto' => [parent::class, 'prodotto', null, 16],
        'quantita' => [parent::class, 'quantita', null, 16],
        'scadenza' => [parent::class, 'scadenza', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
